/**
 * Create transparent PNG derivatives for classified white-background packshots.
 * Never overwrites source assets. Regenerates derived-packshot-map.ts.
 *
 * Usage (from web/):
 *   npx tsx scripts/derive-packshot-transparent.ts --brand mideer
 *   npx tsx scripts/derive-packshot-transparent.ts --sku MD3423,MD3424
 *   npx tsx scripts/derive-packshot-transparent.ts --brand mideer --force
 *
 * Only processes likelyImageType === packshot_white.
 * Lifestyle / ambiguous are left untouched.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { loadEnv } from "./load-env";
import {
  classifyImageBuffer,
  deriveTransparentPackshotPng,
  derivedPackshotPublicPath,
  sourceImageKeyFromUrl,
} from "../lib/products/packshot-bg";

type Row = {
  id: string;
  sku: string;
  name: string;
  brand: string | null;
  image_url: string;
};

function parseArg(flag: string): string | null {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return null;
  return process.argv[idx + 1] ?? null;
}

function hasFlag(flag: string): boolean {
  return process.argv.includes(flag);
}

async function fetchBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

function writeManifest(map: Record<string, string>) {
  const sorted = Object.keys(map)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
    .join("\n");

  const body = `/**
 * Auto-generated by scripts/derive-packshot-transparent.ts
 * Maps source storage filename → public transparent PNG path.
 * Do not edit by hand — re-run the derive script.
 */
export const DERIVED_PACKSHOT_BY_SOURCE_KEY: Readonly<Record<string, string>> = {
${sorted}
};
`;
  const mapPath = resolve(
    process.cwd(),
    "lib/products/derived-packshot-map.ts",
  );
  writeFileSync(mapPath, body);
  console.log(`Updated ${mapPath} (${Object.keys(map).length} entries)`);
}

function loadExistingMapFromDerivedDir(derivedDir: string): Record<string, string> {
  const map: Record<string, string> = {};
  if (!existsSync(derivedDir)) return map;
  for (const file of readdirSync(derivedDir)) {
    if (!file.toLowerCase().endsWith(".png")) continue;
    const stem = file.replace(/\.png$/i, "");
    // Prefer matching common source extensions via stem — map keys are full source filenames.
    // We rebuild keys from product rows; this only preserves public paths for orphaned files.
    map[`__stem__:${stem}`] = `/product-images/derived/${file}`;
  }
  return map;
}

async function main() {
  loadEnv();
  const brandFilter = parseArg("--brand");
  const skuFilter = parseArg("--sku")
    ?.split(",")
    .map((s) => s.trim().toUpperCase())
    .filter(Boolean);
  const force = hasFlag("--force");

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) {
    console.error("Missing Supabase env");
    process.exit(1);
  }

  const sb = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  let query = sb
    .from("products")
    .select("id, sku, name, brand, image_url")
    .eq("assortment_status", "active")
    .not("image_url", "is", null)
    .order("sku");

  if (brandFilter) query = query.ilike("brand", `%${brandFilter}%`);

  const { data, error } = await query;
  if (error) {
    console.error(error);
    process.exit(1);
  }

  let rows = (data ?? []) as Row[];
  if (skuFilter?.length) {
    const set = new Set(skuFilter);
    rows = rows.filter((r) => set.has(r.sku.toUpperCase()));
  }

  const derivedDir = resolve(process.cwd(), "public/product-images/derived");
  mkdirSync(derivedDir, { recursive: true });

  const map: Record<string, string> = {};
  // Seed map from existing derived PNGs that match current product source keys
  const existingByStem = loadExistingMapFromDerivedDir(derivedDir);

  let processed = 0;
  let skippedLifestyle = 0;
  let skippedAmbiguous = 0;
  let skippedExisting = 0;
  let failed = 0;

  for (const row of rows) {
    const sourceKey = sourceImageKeyFromUrl(row.image_url);
    const stem = sourceKey.replace(/\.[^.]+$/i, "");
    const outPath = join(derivedDir, `${stem}.png`);
    const publicPath = derivedPackshotPublicPath(sourceKey);

    if (existsSync(outPath) && !force) {
      map[sourceKey] = publicPath;
      skippedExisting++;
      console.log(`${row.sku} KEEP existing derivative`);
      continue;
    }

    try {
      const buf = await fetchBuffer(row.image_url);
      const metrics = await classifyImageBuffer(buf);

      if (metrics.kind === "lifestyle") {
        skippedLifestyle++;
        console.log(`${row.sku} SKIP lifestyle — ${row.name.slice(0, 40)}`);
        continue;
      }
      if (metrics.kind === "ambiguous") {
        skippedAmbiguous++;
        console.log(`${row.sku} SKIP ambiguous — ${row.name.slice(0, 40)}`);
        continue;
      }

      const { png } = await deriveTransparentPackshotPng(buf);
      writeFileSync(outPath, png);
      map[sourceKey] = publicPath;
      processed++;
      console.log(
        `${row.sku} OK packshot → ${basename(outPath)} (${metrics.width}x${metrics.height})`,
      );
    } catch (e) {
      failed++;
      console.error(
        `${row.sku} FAIL`,
        e instanceof Error ? e.message : e,
      );
    }
  }

  // Preserve any previously mapped stems that still have files but weren't in this run
  for (const [k, v] of Object.entries(existingByStem)) {
    if (!k.startsWith("__stem__:")) continue;
    const stem = k.slice("__stem__:".length);
    const already = Object.values(map).some((p) => p.endsWith(`/${stem}.png`));
    if (!already && existsSync(join(derivedDir, `${stem}.png`))) {
      // Cannot invent source key; ignore orphans without a product row in this run
      void v;
    }
  }

  writeManifest(map);

  console.log("\nDone", {
    processed,
    skippedExisting,
    skippedLifestyle,
    skippedAmbiguous,
    failed,
    mapped: Object.keys(map).length,
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
