/**
 * Auto-generated by scripts/derive-packshot-transparent.ts
 * Maps source storage filename → public transparent PNG path.
 * Do not edit by hand — re-run the derive script.
 */
export const DERIVED_PACKSHOT_BY_SOURCE_KEY: Readonly<Record<string, string>> = {
  "CT0615.jpg": "/product-images/derived/CT0615.png",
  "CT0616.jpg": "/product-images/derived/CT0616.png",
  "CT0624.png": "/product-images/derived/CT0624.png",
  "CT7013.jpg": "/product-images/derived/CT7013.png",
  "MD1039.png": "/product-images/derived/MD1039.png",
  "MD1475.jpg": "/product-images/derived/MD1475.png",
  "MD1478.jpg": "/product-images/derived/MD1478.png",
  "MD1644.jpg": "/product-images/derived/MD1644.png",
  "MD1645.jpg": "/product-images/derived/MD1645.png",
  "MD1672.jpg": "/product-images/derived/MD1672.png",
  "MD1745.png": "/product-images/derived/MD1745.png",
  "MD2422.png": "/product-images/derived/MD2422.png",
  "MD3423.png": "/product-images/derived/MD3423.png",
  "MD3424.png": "/product-images/derived/MD3424.png",
  "MD3428.png": "/product-images/derived/MD3428.png",
  "MD4214.png": "/product-images/derived/MD4214.png",
};
